---
title: "hw1"
author: "Mitul Marimuthu"
date: "2026-04-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadset}
data <- read.csv("./datasets/Dataset.csv")
```

```{r eval = FALSE}
class(data['Energy_Consumption_kWh'])
head(data['Energy_Consumption_kWh'])
```


```{r nullmodel}
null_model <- lm(Energy_Consumption_kWh ~ 1, data = data)
```

```{r nullmodelsummary}
null_model$coefficients
mean(data$Energy_Consumption_kWh)
sse_null <- sum(resid(null_model)^2)
sse_null
summary(null_model)
```


```{r simplelinreg}
sim_lin_reg = lm(data$Energy_Consumption_kWh ~ data$Temperature_C, data = data)
```

```{r slrsummary}
summary(sim_lin_reg)
sse_lin <- sum(resid(sim_lin_reg)^2)
```
```{r comparison}
sse_null
sse_lin
```

The simple linear regression model has a smaller SSE, therefore it is a better model. 

```{r slrscatt}
plot(data$Temperature_C, data$Energy_Consumption_kWh, xlab = "Temperature (C)",
     ylab = "Energy Consumption (kWh)", main = "Temperature vs Energy Consumption")
abline(null_model, col = "red")
abline(sim_lin_reg, col = "blue")
```

